apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]  # Empty string indicates core API group
    resources: ["*"]  # Grant access to all resources
    verbs: ["get", "list"]     # Grant all verbs (get, list, watch, create, update, delete)

