apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default  # Replace with your namespace if different
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
